### PR TITLE
Ss/gh pages edit

### PR DESCRIPTION
**Pull request by sascala**
@aquamatthias I edited the metronome site so that users aren't confused / disappointed. I built the site locally and everything looks good, except I wasn't able to successfully generate the HTML from the raml file. I ran the `raml2html` script directly and got an error, and tried the `update_docs.sh` script for good measure and got the same error:
```
Error: _sourceToRamlObj: only RAML 1.0 is supported!
    at raml.loadApi.then (/Users/suzanne/.nvm/versions/node/v6.3.1/lib/node_modules/raml2html/node_modules/raml2obj/index.js:219:17)`
```

Would you mind building the site locally to see if it looks good to you? And if you're not the right person to assign this to, please reassign. And if you have a hint on how to convert the raml to HTML, please let me know!

### CODE REVIEW

**Comment by aquamatthias** [comment]
@sascala Let me try to rebuild gh-pages.

**Comment by aquamatthias** [comment]
@sascala I merged this PR and published the github page.
I noticed, that http://dcos.github.io/metronome/docs/ still looks odd - can you change this?
Also: Can you please add a link to the REST-API in `README.md` ?
Thanks!

**Comment by sascala** [comment]
@aquamatthias Thanks for merging this.

Happy to add an API link to the readme.

Can you be more specific about what looks odd? I don't love the look of the site, mind you. :-).

**Comment by aquamatthias** [comment]
Hey @sascala  - I think I still saw some pages with the old navbar. It is gone now - probably a caching issue - all good. Thanks!

**Comment by sascala** [comment]
Glad we've finally got that done!

**Pull request merged**
