### PR TITLE
corrected link to jobs docs

### PR DESCRIPTION
**Pull request by sascala**
@aquamatthias  This link will be live as soon as 1.8 EAs for the public.

### CODE REVIEW

**Comment by sascala** [comment]
@aquamatthias This page is now live: https://dcos.io/docs/1.8/usage/jobs

**Comment by tobilg** [comment]
@sascala There's a typo: `chron` instead of `cron`. Thanks!

**Comment by sascala** [comment]
@tobilg Thanks for noticing! Fixing...

**Comment by kensipe** [comment]
LGTM

**Pull request merged**
