### PR TITLE
Always return history info (fallback to empty history, if not existent)

### PR DESCRIPTION
**Pull request by aquamatthias**

### CODE REVIEW

**Comment by kensipe** [comment]
LGTM and looks cleaner!   I'll test, then merge.

**Comment by kensipe** [comment]
It does test out :(

output:

```
cli(git:ken/metronome)$ http http://localhost:9000/v1/jobs?embed=history
HTTP/1.1 200 OK
Content-Length: 239
Content-Type: application/json
Date: Sun, 31 Jul 2016 17:22:00 GMT

[
    {
        "description": "electrifying rodent", 
        "id": "pikachu", 
        "labels": {}, 
        "run": {
            "artifacts": [], 
            "cmd": "sleep 1", 
            "cpus": 0.01, 
            "disk": 0, 
            "env": {}, 
            "maxLaunchDelay": 3600, 
            "mem": 32, 
            "placement": {
                "constraints": []
            }, 
            "restart": {
                "policy": "NEVER"
            }, 
            "volumes": []
        }
    }
]

```

**Comment by aquamatthias** [comment]
Will look into this.

**Comment by aquamatthias** [comment]
A Map with defaultValue will return None if you use get.
I rewrote the solution to always return a value, if history is set.

**Comment by kensipe** [comment]
ok... this is better but we have nulls in json.  Is that what we want?  here is the output:

```
 http http://localhost:9000/v1/jobs?embed=history
HTTP/1.1 200 OK
Content-Length: 379
Content-Type: application/json
Date: Tue, 16 Aug 2016 23:52:13 GMT

[
    {
        "description": "electrifying rodent",
        "history": {
            "failedFinishedRuns": [],
            "failureCount": 0,
            "lastFailureAt": null,
            "lastSuccessAt": null,
            "successCount": 0,
            "successfulFinishedRuns": []
        },
        "id": "pikachu",
        "labels": {},
        "run": {
            "artifacts": [],
            "cmd": "sleep 1",
            "cpus": 0.01,
            "disk": 0,
            "env": {},
            "maxLaunchDelay": 3600,
            "mem": 32,
            "placement": {
                "constraints": []
            },
            "restart": {
                "policy": "NEVER"
            },
            "volumes": []
        }
    }
]
```

**Comment by kensipe** [comment]
this works fine with the CLI and LGTM.  I'll merge.

**Pull request merged**
