### PR TITLE
reenable fatal warnings

### PR DESCRIPTION
**Pull request by alenkacz**

### CODE REVIEW

**Comment by kensipe** [comment]
why is this necessary?   what happened to https://github.com/dcos/metronome/pull/264 ?

**Comment by kensipe** [comment]
`sbt universal:packageZipTarball` has checks not invoked by compile or test which result in  warnings of unused imports which are in generated filees.   Examples:

```
[error] `silencer-plugin` was enabled but the @silent annotation was not found on classpath - have you added `silencer-lib` as a library dependency?
[error] /Users/kensipe/projects/metronome/api/target/scala-2.12/routes/main/controllers/ReverseRoutes.scala:8:34: Unused import
[error] import _root_.controllers.Assets.Asset
[error]                                  ^
[error] /Users/kensipe/projects/metronome/api/target/scala-2.12/routes/main/controllers/ReverseRoutes.scala:9:42: Unused import
[error] import _root_.dcos.metronome.api.Binders._
[error]                                          ^
[info] No documentation generated with unsuccessful compiler run
[error] one error found
[error] /Users/kensipe/projects/metronome/api/target/scala-2.12/routes/main/controllers/javascript/JavaScriptReverseRoutes.scala:8:34: Unused import
[error] import _root_.controllers.Assets.Asset
[error]                                  ^
[error] /Users/kensipe/projects/metronome/api/target/scala-2.12/routes/main/controllers/javascript/JavaScriptReverseRoutes.scala:9:42: Unused import
[error] import _root_.dcos.metronome.api.Binders._
[error]                                          ^
[error] /Users/kensipe/projects/metronome/api/target/scala-2.12/routes/main/dcos/metronome/api/v0/controllers/ReverseRoutes.scala:8:34: Unused import
[error] import _root_.controllers.Assets.Asset
[error]                                  ^
[error] /Users/kensipe/projects/metronome/api/target/scala-2.12/routes/main/dcos/metronome/api/v0/controllers/javascript/JavaScriptReverseRoutes.scala:8:34: Unused import
[error] import _root_.controllers.Assets.Asset
[error]                                  ^
[error] /Users/kensipe/projects/metronome/api/target/scala-2.12/routes/main/dcos/metronome/api/v1/controllers/ReverseRoutes.scala:8:34: Unused import
[error] import _root_.controllers.Assets.Asset
[error]                                  ^
[error] /Users/kensipe/projects/metronome/api/target/scala-2.12/routes/main/dcos/metronome/api/v1/controllers/javascript/JavaScriptReverseRoutes.scala:8:34: Unused import
[error] import _root_.controllers.Assets.Asset
[error]                                  ^
```

I've cleaned up the others with #272  

We either need to ignore the generated code or remove this PR me thinks.

**Comment by kensipe** [comment]
rebased after code cleanup

**Comment by timcharper** [comment]
Looks like it was already merged

Something I'll say on the subject is that fatal warnings breaks `sbt console`, which is pretty sad.

**Comment by kensipe** [comment]
yeah... lets not

**Pull request closed without merging**
